theme: jekyll-theme-hacker
title: GitHub Actions Workshop
description: |
  A hands-on workshop designed to help you master GitHub Actions. Learn how to automate workflows, run tests, deploy applications, and more. This repository contains all the labs, exercises, and example workflows to get you started with continuous integration and continuous deployment using GitHub Actions.
