name: ASP.NET Web App Build and Deploy

on:
  push:
    paths:
      - '.github/workflows/aspnet-webapp-deploy.yml'
      - 'src/dotnet/WebApp/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/dotnet/WebApp
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '8.x'

      - name: Build code
        run: dotnet build --configuration Release

      - name: Publish code
        run: dotnet publish -c Release --property:PublishDir="${{runner.temp}}/webapp"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: .net-web-app # Artifact name
          path: ${{runner.temp}}/webapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      package-name: .net-web-app
      app-name: github-actions-webapp
      deployment-slot: production

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.1.8
        with:
          name: .net-web-app # Artifact name

      - name: List files in root directory
        run: |
          ls -al
        shell: bash

      - name: Secret Information
        run: echo "Value of secret matches - ${{ secrets.AZURE_PUBLISH_PROFILE  == 'AZ_PRROFILE' }}"

      - name: Print name of App Service to deploy to
        run: echo "App will be deployed to ${{ env.app-name }}"
