name: Reusable Workflow Echo Caller

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/reusable-workflow-echo-caller.yml'
jobs:
  call:
    uses: ./.github/workflows/reusable-workflow-echo.yml
    with:
      my-input: 'Hello, world!'
