name: ASP.NET Web App Build and Deploy

on:
  push:
    paths:
      - '.github/workflows/aspnet-webapp-deploy.yml'
      - 'src/dotnet/WebApp/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/dotnet/WebApp
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '8.x'

      - name: Build code
        run: dotnet build --configuration Release

      - name: Publish code
        run: dotnet publish -c Release --property:PublishDir="${{runner.temp}}/webapp"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: aspnet-web-app # Artifact name
          path: ${{runner.temp}}/aspnet-web-app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      package-name: aspnet-web-app
      app-name: github-actions-workshop-aspnet-webapp
      deployment-slot: production

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.1.8
        with:
          name: aspnet-web-app # Artifact name

      - name: Set up Azure Web App Deploy Action
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.app-name }} # Name of your Azure Web App
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} # Azure publish profile secret
          package: ${{ runner.temp }}/aspnet-web-app # Path to the artifact generated from the build job
          slot-name: ${{ env.deployment-slot }} # Deployment slot name (e.g., 'production')

