name: ASP.NET Web App Build and Deploy

on:
  push:
    paths:
      - '.github/workflows/aspnet-webapp-deploy.yml'
      - 'src/dotnet/WebApp/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/dotnet/WebApp
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '8.x'

      - name: Build code
        run: dotnet build --configuration Release

      - name: Publish code
        run: dotnet publish -c Release --property:PublishDir="${{ runner.temp }}/webapp"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: aspnet-web-app
          path: ${{ runner.temp }}/webapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      app-name: github-actions-workshop-aspnet-webapp # Azure App Service name

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4.1.8
        with:
          name: aspnet-web-app # Ensure artifact name matches the one uploaded in the build job

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.app-name }} # Azure Web App name
          publish-profile: ${{ secrets.ASPNET_WEBAPP_PUBLISH_PROFILE }} # Azure publish profile secret
