name: ASP.NET Weather Web Api Publish Docker Image
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/aspnet-weather-webapi-publish-docker-image.yml'
      - 'src/dotnet/Weather.WebApi/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/dotnet/Weather.WebApi
    permissions:
      contents: read
      packages: write # Required for creating packages
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build ASP.NET Weather Web API
        run: dotnet build

      - name: Build Local Docker Image
        run: docker image build -t weather-webapi .

      - name: List Docker Images
        run: docker image ls

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Image to latest
        run: docker tag weather-webapi prasadhonrao/weather-webapi:latest

      - name: Push Image with latest tag to Docker Hub Registry
        run: docker push prasadhonrao/weather-webapi:latest
