name: Package Artifact
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/package-artifact.yml'
      - 'src/python/upper_project/**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required for creating packages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List .NET Runtimes
        run: dotnet --list-runtimes

      - name: Build .NET WebApi
        run: dotnet build
        working-directory: ./src/dotnet/Weather.WebApi

      - name: Build Local Docker Image
        run: docker image build -t weather-webapi .
        working-directory: ./src/dotnet/Weather.WebApi

      - name: List Docker Images
        run: docker image ls

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Image to latest
        run: docker tag weather-webapi ghcr.io/prasadhonrao/weather-webapi:latest

      - name: Tag Image to branch
        run: docker tag weather-webapi ghcr.io/prasadhonrao/weather-webapi:${{ github.ref_name }}

      - name: Push Image with latest tag to GitHub Container Registry
        run: docker push ghcr.io/prasadhonrao/weather-webapi:latest

      - name: Push Image with branch tag to GitHub Container Registry
        run: docker push ghcr.io/prasadhonrao/weather-webapi:${{ github.ref_name }}
