name: Python Upper App Unit Test and Upload Artifact

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/python-unit-test-and-upload-artifact.yml'
      - 'src/python/upper_project/**'

jobs:
  test:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./src/python/upper_project
        shell: pwsh # Using PowerShell shell
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Print Python version
        run: |
          python --version  # Run Python version check in PowerShell

      - name: Print pip version
        run: |
          python -m pip --version  # Run pip version check in PowerShell

      - name: Unit test
        run: |
          python -m unittest discover tests  # Run unit tests in PowerShell

  upload:
    runs-on: self-hosted
    needs: test
    defaults:
      run:
        working-directory: ./src/python/upper_project
        shell: pwsh # Using PowerShell shell
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Check if pyinstaller is installed
        run: |
          if (-not (Get-Command pyinstaller -ErrorAction SilentlyContinue)) {
            Write-Host "PyInstaller not found, installing..."
            pip install pyinstaller
          } else {
            Write-Host "PyInstaller is already installed."
          }

      - name: Build executable
        run: |
          pyinstaller --onefile upper/upper.py  # Build the executable in PowerShell

      - name: List dist directory contents
        run: |
          Get-ChildItem -Path ./dist  # List contents of dist directory in PowerShell

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: upper-executable
          path: ./src/python/upper_project/dist/upper.exe # Use full path to the executable

