name: Python Upper App CI/CD on Ubuntu Runner
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/python-upper-app-ci-cd-on-ubuntu-runner.yml'
      - 'src/python/upper_project/**'
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Get all the files in current directory before checkout
        run: pwd && ls -al

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Files In Directory
        run: pwd && ls -al

      - name: Print Python Version
        run: python --version

      - name: Print pip Version
        run: python -m pip --version

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Unit Test
        run: python -m unittest discover tests
        working-directory: src/python/upper_project
  upload:
    runs-on: windows-latest
    needs: test
    defaults:
      run:
        working-directory: ./src/python/upper_project
        shell: pwsh # Using PowerShell shell
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pyinstaller
        run: |
          if (-not (Get-Command pyinstaller -ErrorAction SilentlyContinue)) {
            Write-Host "PyInstaller not found, installing..."
            pip install pyinstaller
          } else {
            Write-Host "PyInstaller is already installed."
          }

      - name: Build Executable
        run: |
          pyinstaller --onefile upper/upper.py  # Build the executable in PowerShell

      - name: List Files In Directory
        run: |
          Get-ChildItem -Path ./dist  # List contents of dist directory in PowerShell

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: upper-executable
          path: ./src/python/upper_project/dist/upper.exe # Use full path to the executable

      - name: Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: src/python/upper_project/dist/*
          body: 'Binaries for the upper (python) command line tool!!!'
          tag_name: 'python-upper-${{ github.ref_name }}'
