name: Python Unit Test and Upload Artifact on Self-Hosted Runner
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/python-unit-test-and-upload-artifact.yml'
      - 'src/python/upper_project/**'
jobs:
  test:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./src/python/upper_project
        shell: C:\Program Files\Git\bin\bash.exe
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Print Python version
        run: |
          echo "Printing Python version..."
          python --version  # This will work correctly in Git Bash

      - name: Print pip version
        run: |
          echo "Printing pip version..."
          python -m pip --version

      - name: Unit test
        run: |
          echo "Running unit tests..."
          python -m unittest discover tests  # Running the unit tests
  upload:
    runs-on: self-hosted
    needs: test
    defaults:
      run:
        working-directory: ./src/python/upper_project
        shell: C:\Program Files\Git\bin\bash.exe
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Check if pyinstaller is installed
        run: |
          if ! command -v pyinstaller &> /dev/null
          then
            echo "PyInstaller not found, installing..."
            pip install pyinstaller
          else
            echo "PyInstaller is already installed."
          fi

      - name: Build executable
        run: |
          echo "Building the executable..."
          pyinstaller --onefile upper/upper.py

      - name: List dist directory contents
        run: |
          echo "Listing dist directory contents..."
          ls -l ./dist  # Ensures you're checking the correct path

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: upper-executable
          path: /dist/upper.exe
