name: Python Upper Build and Test
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/python-upper-build-test.yml'
      - 'src/python/upper_project/**'
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Get all the files in current directory before checkout
        run: pwd && ls -al

      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Get all the files in current directory after checkout
        run: pwd && ls -al

      - name: Print Python version
        run: python --version

      - name: Print pip version
        run: python -m pip --version

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Unit test
        run: python -m unittest discover -p '*_test.py'
        working-directory: src/python/upper_project

      - name: Build upper package
        run: python setup.py sdist bdist_wheel
        working-directory: src/python/upper_project

      - name: List dist directory
        run: ls src/python/upper_project/dist

      - name: Install upper package
        run: python -m pip install dist/upper_project-0.1.0-py3-none-any.whl
        working-directory: src/python/upper_project

      - name: Run upper package
        run: upper gihub actions is awesome
