name: Python Unit Test and Upload Artifact on Self-Hosted Runner
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/python-unit-test-and-upload-artifact.yml'
      - 'src/python/upper_project/**'
jobs:
  test:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./src/python/upper_project
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Print Python version
        run: python --version

      - name: Print pip version
        run: python -m pip --version

      - name: Unit test
        run: python -m unittest discover tests
  upload:
    runs-on: self-hosted
    needs: test
    defaults:
      run:
        working-directory: ./src/python/upper_project
        shell: pwsh
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Check if pyinstaller is installed
        run: |
          if ! command -v pyinstaller &> /dev/null
          then
            echo "PyInstaller not found, installing..."
            pip install pyinstaller
          else
            echo "PyInstaller is already installed."
          fi

      - name: Build executable
        run: pyinstaller --onefile upper/upper.py

      - name: List dist directory contents
        run: ls -l ./dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: upper-executable
          path: /dist/upper.exe
