name: Release Artifact Multiple OS

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/release-artifact-multiple-os.yml'
      - 'src/python/upper_project/**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write # required to create releases
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd src/python/upper_project
          pip install pyinstaller

      - name: Build executable
        run: |
          cd src/python/upper_project
          pyinstaller --onefile upper/upper.py
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: src/python/upper_project/dist/*
          name: 'build-${{ matrix.os }}'

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write # required to create releases
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-ubuntu-latest
          path: ./dist/ubuntu

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-windows-latest
          path: ./dist/windows

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-macos-latest
          path: ./dist/macos

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/**
          body: 'Binaries for the upper (python) command line tool!!!'
          tag_name: ${{ github.ref_name }}
          name: 'python-upper-${{ github.ref_name }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Release
        run: |
          echo "Release created: ${{ steps.create_release.outputs.html_url }}"
