name: Release Artifact
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/release-artifact.yml'
      - 'src/python/upper_project/**'
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write # required to create releases
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd src/python/upper_project
          pip install pyinstaller

      - name: Build executable
        run: |
          cd src/python/upper_project
          pyinstaller --onefile upper/upper.py
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: upper-executable
          path: src/python/upper_project/dist/upper.exe

      - name: Release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: src/python/upper_project/dist/*
          body: 'Binaries for the upper (python) command line tool!!!'
          tag_name: 'python-upper-${{ github.ref_name }}'
