name: Scheduled Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes. You can use https://crontab.guru/ to generate cron expressions
  push:
    paths:
      - '.github/workflows/scheduled-workflow.yml'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Current time is $(date)"
