name: Upload Artifact
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/upload-artifact.yml'
      - 'src/python/upper_project/**'
jobs:
  build-and-upload:
    runs-on: windows-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd src/python/upper_project
          pip install pyinstaller

      - name: Build executable
        run: |
          cd src/python/upper_project
          pyinstaller --onefile upper/upper.py
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: upper-executable
          path: src/python/upper_project/dist/upper.exe
