name: Upload and Download Artifact Multiple OS

on:
  push:
    paths:
      - '.github/workflows/upload-and-download-artifact-multiple-os.yml'
      - 'src/dotnet/WebApp/**'
  workflow_dispatch:

jobs:
  upload:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./src/dotnet/WebApp
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: '8.x'

      - name: Build Code
        run: dotnet build --configuration Release

      - name: Publish Code
        shell: bash
        run: |
          # Set the publish directory based on OS
          if [ "$RUNNER_OS" = "Windows" ]; then
            export PUBLISH_DIR="${{ runner.temp }}\\myapp"
          else
            export PUBLISH_DIR="${{ runner.temp }}/myapp"
          fi

          # Publish the application
          mkdir -p "$PUBLISH_DIR"
          dotnet publish -c Release --output "$PUBLISH_DIR"

      - name: Verify Publish Directory
        shell: bash
        run: |
          echo "Contents of publish directory:"
          if [ "$RUNNER_OS" = "Windows" ]; then
            ls "$PUBLISH_DIR"
          else
            ls -la "$PUBLISH_DIR"
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: '.net-web-app-${{ runner.os }}'
          path: ${{ runner.temp }}/myapp

  download:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: upload
    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4.1.8
        with:
          name: '.net-web-app-${{ matrix.os }}'

      - name: List Files in Downloaded Artifact
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            ls
          else
            ls -la
          fi
